### ISSUE TITLE
Class Names

### ISSUE THREAD

**Issue by zachfedor** [DomBouman/more-css-practice#3]
https://github.com/DomBouman/more-css-practice/blob/3c00897f16dc01ca1bb0b6ccd60493ede9851b95/github/index.html#L17-L18

You should probably use more descriptive class names. When you're working with other people, they should be able to look at your CSS and have a pretty good idea of what elements the rules are applying to. If they see:
```css
.sweet { ... }
.wow { ... }
```
They're going to have to search through all your HTML to spot those words, and they'll resent you for it, haha. Try using names that describe what the element does, like `nav-list`.

**Comment by DomBouman** [comment]
I didn't even think about it when it comes to the fact of other people looking at my code. Thanks
