### ISSUE TITLE
Headings as sections

### ISSUE THREAD

**Issue by zachfedor** [DomBouman/more-css-practice#4]
https://github.com/DomBouman/more-css-practice/blob/3c00897f16dc01ca1bb0b6ccd60493ede9851b95/instagram/index.html#L26

You could have used a better order for your `<h?>` elements. If the browser made an outline of your page, it would look like this according to your headings:
```
1. About
    a. Legal
        i. About Us
```
Which isn't really a good representation of what the page is for. A better outline might be something like:
```
1. About Us
    a. The Team
        i. Kevin Systrom (CEO, co-founder)
        ii. Mike Krieger (CTO, co-founder)
```
Notice how each child is a sub-section of it's parent. That's how headings are supposed to work. Anything on the `a-b-c` level is under the main level and should be given an `<h2>` tag. Anything on the `i-ii-iii` level is a sub-section of something on the `a-b-c` level and should be given an `<h3>` tag. Notice how the nav sidebar isn't even showing? That's because it's not really part of the page content, it's just a helpful way to navigate to other pages. So there shouldn't be headings in the nav.

**Comment by DomBouman** [comment]
Thank you. I went through and changed some stuff so hopefully it looks and works a little better.
