### ISSUE TITLE
Using font weight/link over bold

### ISSUE THREAD

**Issue by zachlehman99** [DomBouman/more-css-practice#5]
https://github.com/DomBouman/more-css-practice/blob/66e671662b452bd064a88c920bd25a81cf862abe/instagram/index.html#L28-L32

You could get rid of the b tag and use font weight in CSS to make it bold like you wanted to or I think it was suppose to be a link so you could use a href instead.

**Comment by DomBouman** [comment]
thanks for the advise! never really thought of that. Your great!
